### ISSUE TITLE
Citing stag in research

### ISSUE THREAD

**Issue by erleria** [staglibrary/stag#130]
Hi,

I would like to know if you have any bibtex template or any wish on how to cite STAG in a research paper

**Comment by pmacg** [comment]
Hi, thanks for your interest. You can cite the STAG library with the following bibtex entry.

```
@article{stag,
    author       = {Peter Macgregor and He Sun},
    title        = {Spectral Toolkit of Algorithms for Graphs: Technical Report {(1)}},
    journal      = {CoRR},
    volume       = {abs/2304.03170},
    year         = {2023},
    doi          = {10.48550/arXiv.2304.03170},
    eprinttype    = {arXiv},
    eprint       = {2304.03170},
}
```

This is a reference to our first technical report, which you can read here: https://arxiv.org/abs/2304.03170.
